version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - ENV=development
    volumes:
      - ./backend:/app
    working_dir: /app

  # Add database service when needed
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: physical_revelry
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: